complete -f -c colors -l help -s h -d "Show help"
complete -f -c colors -l examples -d "Display fish syntax color examples"
complete -f -c colors -l variables -d "Display fish syntax color variables"
complete -f -c colors -l ansi -d "Display ANSI colors table (default option)"
complete -f -c colors -l aixterm -s h -d "Display aixterm high intensity colors table"
complete -f -c colors -l 256colors -s h -d "Display 256 colors table"
